import discord
import os
from dotenv import load_dotenv
from discord import app_commands


intents = discord.Intents.default()
client = discord.Client(intents=intents)
tree = app_commands.CommandTree(client)

@tree.command(name = "diffusion", description = "gives a user an image generated by stable-diffusion", guild=discord.Object(id=1113884879252369438))
async def diffusion(self, diffusionprompt: str):
    output = replicate.run(
        "stability-ai/stable-diffusion:",
        input={"prompt":diffusionprompt}
    )
await self.response.send_message(output)
@client.event
async def on_ready():
    print("Bot has booted!")
    await tree.sync(guild=discord.Object(id=1113884879252369438))


# load_dotenv()
# print(os.getenv("TOKEN"))
client.run(os.getenv("TOKEN"))
