import discord
# import os
# from dotenv import load_dotenv
from discord import app_commands
from torch import autocast
from diffusers import StableDiffusionPipeline

intents = discord.Intents.default()
client = discord.Client(intents=intents)
tree = app_commands.CommandTree(client)

@tree.command(name = "diffusion", description = "gives a user an image generated by stable-diffusion", guild=discord.Object(id=1113884879252369438))
async def diffusion(self, diffusionprompt: str):
    await self.response.send_message("Sending image..")
    pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4",use_auth_token=False).to("cuda")
    prompt = diffusionprompt
    with autocast("cuda"):
        image = pipe(prompt+" --W 64 --H 64")
    image.save(diffusion.png)
    await client.send_message(client.get_channel("1113884879789236306"), file=discord.File('diffusion.png'))
@client.event
async def on_ready():
    print("Bot has booted!")
    await tree.sync(guild=discord.Object(id=1113884879252369438))


# load_dotenv()
# print(os.getenv("TOKEN"))
client.run("MTExOTQ1MzU1OTg3MjgzNTU4NA.GYH3tb.CRi3tnFlV6Ms8BH6WOcDVpLKqcQsj9pp1ugP8A")